[package]
name = "async-component"
description = "Compose ui components with Stream"
version = "0.1.1"
edition = "2021"
readme = "../readme.md"

authors = [
    "storycraft <storycraft@pancake.sh>"
]
license = "Apache-2.0"
repository = "https://github.com/storycraft/async-component"

[dependencies]
futures = "0.3.25"
pin-project = "1"
async_cell = "0.2.1"
async-component-macro = { version = "0.1.0", path = "../async-component-macro" }
bitflags = "1.3.2"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
