[package]
name = "gui-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
async-component = { path = "../../async-component" }

futures = "0.3.25"

winit = "0.27.5"
raqote = "0.8.1"
pixels = "0.10.0"